Added indentation support
fleather-editor/fleather pull request #12
Opened 2022-06-26 19:29 UTC by Amir-P

2022-06-28 14:56 UTC, amantoux requested changes
Very nice feature 😀
I've put some suggestions let me know your thoughts

2022-06-28 14:56 UTC, amantoux commented on packages/fleather/lib/src/widgets/editable_text_block.dart
> +      leadingWidgets.add(_NumberPoint(
Sounds reasonable that `_NumberPoint` takes the displayed index as parameter rather than 0-based index here. Don't you think?

2022-07-02 08:54 UTC, Amir-P commented on packages/parchment/lib/src/document/attributes.dart
> +const _maxIndentationLevel = 8;
- I think that's a deprecated style. Refer to: https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters
- In QuillJS the max depth for lists is 8 and for paragraphs it's unlimited. I guess 8 is a good number in terms of maximum compatibility with QuillJS but WDYT?
@amantoux

2022-07-03 19:42 UTC, amantoux commented on packages/parchment/lib/src/document/attributes.dart
> +const _maxIndentationLevel = 8;
- OK;  my bad, thanks for the update
- If you want to guarantee compatibility with QuillJS, ok then (I'm not going to fight on this one)

2022-07-04 04:30 UTC, Amir-P commented on packages/fleather/lib/src/widgets/editable_text_block.dart
> +    final leadingWidgets = <Widget>[];
Can you clarify this? @amantoux

2022-07-05 20:00 UTC, Amir-P commented on packages/fleather/lib/src/widgets/editable_text_block.dart
> +    final levels = <int>[];
I think it's easier this way. We are stacking levels and indexes and we have repetitive levels with different indexes, so neither level and index can't be a key in this Map. Hope I got what you're saying right. @amantoux

2022-07-08 18:19 UTC, amantoux requested changes

2022-07-18 10:38 UTC, Amir-P commented
Can you check my last commit? @amantoux

2022-07-19 07:45 UTC, amantoux requested changes
@Amir-P I've added a comment

2022-07-19 07:45 UTC, amantoux commented on packages/fleather/lib/src/widgets/editable_text_block.dart
> +    final levels = <int>[];
I had something like that in mind. Hope I'm not missing anything

```dart
for (final element in children) {
  final currentLevel = element.style.get(ParchmentAttribute.indent)?.value ?? 0;
  var currentIndex = 0;

  if (levelsIndexes.containsKey(currentLevel)) {
    currentIndex = levelsIndexes[currentLevel]! + 1;
  }
      
  levelsIndexes[currentLevel] = currentIndex;

  leadingWidgets.add(_NumberPoint(
    number: currentIndex + 1,
    style: theme.paragraph.style,
    width: 32.0,
    padding: 8.0,
  ));
}
```

2022-07-19 08:25 UTC, amantoux approved these changes
LGTM

2022-07-19 08:26 UTC, merged