Added auto text direction
fleather-editor/fleather pull request #13
Opened 2022-06-26 19:47 UTC by Amir-P

From https://github.com/memspace/zefyr/pull/592

2022-07-20 09:36 UTC, amantoux requested changes
@Amir-P I've left some questions and a comment

2022-07-20 10:38 UTC, Amir-P commented on packages/parchment/pubspec.yaml
> +  intl: ^0.17.0
packages from Flutter depend on `intl` so it's pretty reliable. For example [`flutter_localizations`](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml).

2022-07-20 10:43 UTC, Amir-P commented on packages/parchment/lib/src/heuristics/insert_rules.dart
> +      ..retain(1, attributes);
Since direction a line-scoped attribute, we're adding it to the new line character.

2022-07-21 10:38 UTC, amantoux approved these changes
LGTM

2022-07-21 10:38 UTC, merged

2022-09-22 07:19 UTC, Amir-P commented on packages/parchment/lib/src/heuristics/insert_rules.dart
> +      ..retain(1, attributes);
Can you provide steps to reproduce and logs? @cgestes

2022-09-22 09:56 UTC, cgestes commented on packages/parchment/lib/src/heuristics/insert_rules.dart
> +      ..retain(1, attributes);
sorry was using a weird version of quill_delta. took me a bit to figure it out :)

All good :)