Add localizations
fleather-editor/fleather pull request #391
Opened 2024-08-04 12:56 UTC by maelchiotti

Add default localizations with a delegate.

2024-08-04 13:32 UTC, Amir-P commented
I can see that it's marked as a draft. Let me know when it's ready for review.

2024-08-04 13:57 UTC, maelchiotti commented
Indeed, I didn't add localizations for all the strings in the package, that's the only thing that's missing (and fixing tests). I'll tag you when I'm done.

2024-08-09 12:39 UTC, maelchiotti commented on packages/fleather/lib/src/widgets/editor_toolbar.dart
@Amir-P I have an issue with the `FleatherToolbar.basic` factory. The foreground and background color buttons need to be translated, but a `BuildContext` is needed to access the `FleatherLocalizations`. Do you know what would be the best way to build these buttons in a place where a `BuildContext` is available?

2024-08-09 12:58 UTC, Amir-P commented on packages/fleather/lib/src/widgets/editor_toolbar.dart
I would say it might be fine to wrap them with `Builder` widget for now to access the context and localizations data. @maelchiotti

2024-08-09 13:09 UTC, maelchiotti commented on packages/fleather/lib/src/widgets/editor_toolbar.dart
That works indeed.

2024-08-09 13:11 UTC, maelchiotti commented
I've added the other strings, with translations in english and french. Now other languages can be supported just by adding their ARB files.

I've scrolled through all the code to find strings to translate so I hope I didn't miss any. I've also fixed the tests.

So the PR is ready for review now!

2024-08-09 15:28 UTC, Amir-P commented
Are you ok with me pushing a commit on this branch? I had too many improvements in mind that would be a bit time consuming to write and also for you to apply. @maelchiotti

2024-08-09 16:27 UTC, maelchiotti commented
Yes of course you can!

2024-08-09 18:17 UTC, Amir-P commented
Can you please take a look and let me know what you think about the changes? It also would have been better if we could completely ignore generated files from the plugin, but looks like those files don't get generated when `flutter pub get` called on the dependent project. So we have to include them. @maelchiotti

2024-08-09 19:15 UTC, maelchiotti commented
The changes look good to me!

2024-08-09 20:50 UTC, amantoux commented
do you mind if I commit a change to the repo to avoid having the **.g.dart files in the coverage stats?

2024-08-10 18:18 UTC, amantoux commented
> I've added the other strings, with translations in english and french
Cocorico :)

2024-08-10 18:25 UTC, amantoux requested changes
Great to see Fleather in French!
General, I think we should stick to Flutter team practice and put l10n under lib
I have a few comments on the imports

2024-08-10 18:25 UTC, amantoux commented on packages/fleather/lib/src/widgets/editor_toolbar.dart
> +import 'package:fleather/fleather.dart';
We should avoid importing via package for internal files, can you please use relative path?

2024-08-10 18:25 UTC, amantoux commented on packages/fleather/lib/src/widgets/editor_toolbar.dart
> +import 'package:fleather/l10n/l10n.dart';
Same as above

2024-08-10 18:25 UTC, amantoux commented on packages/fleather/lib/src/widgets/link.dart
> +import 'package:fleather/fleather.dart';
use relative path for import?

2024-08-10 18:25 UTC, amantoux commented on packages/fleather/lib/src/widgets/link.dart
> +import 'package:fleather/l10n/l10n.dart';
use relative path for import?

2024-08-10 19:21 UTC, amantoux approved these changes
LGTM
THanks @maelchiotti & @Amir-P

2024-08-10 19:21 UTC, merged

2024-08-10 19:40 UTC, maelchiotti commented
Feel free to tag me if you add a new string anytime, so I can translate it in french directly 😊

2024-08-10 20:28 UTC, amantoux commented
> Feel free to tag me if you add a new string anytime, so I can translate it in french directly 😊

It shouldn't be a problem, I'm French too 🥖

2024-08-10 20:55 UTC, maelchiotti commented
Aha awesome 🥖🥖