v1.20.0
fleather-editor/fleather pull request #444
Opened 2024-12-28 18:08 UTC by amantoux

2024-12-28 19:13 UTC, Amir-P requested changes
Thanks, Alan. I believe we should also have a new release for Parchment as well since we had changes for Flutter 3.27. I also left a tiny comment.

2024-12-28 19:13 UTC, Amir-P commented on packages/fleather/README.md
> +  fleather: ^1.12.0
I think it was meant to be `1.20.0`.

2024-12-28 20:30 UTC, amantoux commented
@Amir-P Can you please review changes?

2024-12-29 06:51 UTC, Amir-P requested changes
One more thing, Alan. We also need to update the parchment version in `/fleather/pubspec.yaml` file.

2024-12-29 18:01 UTC, Amir-P approved these changes
LGTM!

2024-12-29 18:03 UTC, merged