Support for Markdown decoding
fleather-editor/fleather pull request #52
Opened 2022-10-30 20:57 UTC by amantoux

Closes #46

2022-10-31 10:42 UTC, amantoux commented
Hey @Amir-P can you please take a look?

2022-11-09 19:13 UTC, Amir-P requested changes
LGTM although I didn't read decoder line by line. I just have a few small change requests.

2022-11-09 19:13 UTC, Amir-P commented on packages/parchment/lib/src/convert/markdown.dart
> +  Iterable<E> reverse() {
I've tested this functions performance (I suspected it's not going to perform well) and I found that it's way faster to do `iterable.toList().reversed` than to do `iterable.reverse()`. Actually it's 1350 times faster!

2022-11-14 08:10 UTC, amantoux commented on packages/parchment/test/convert/markdown_test.dart
> +    /*test('nested bq', () {
Yes we'll ignore

2022-11-15 20:36 UTC, Amir-P approved these changes
LGTM.

2022-11-15 20:36 UTC, merged