Format link after hitting newline
fleather-editor/fleather pull request #83
Opened 2023-01-06 19:12 UTC by zaynetro

Works in the block and outside the block.

[Screencast from 2023-01-06 21-10-53.webm](https://user-images.githubusercontent.com/627197/211082729-4ee70c20-d2c7-46ab-a2ae-20babe966cfe.webm)

2023-01-07 00:54 UTC, cgestes commented
I am always careful when there are changes involving delta...

had a quick look, it seems the logic is fine. nice :)

2023-01-13 17:11 UTC, zaynetro commented
How can we move this forward?

2023-01-13 17:41 UTC, amantoux commented
I'll try to have a look this week end

2023-01-15 07:26 UTC, amantoux commented on packages/parchment/lib/src/heuristics/insert_rules.dart
> +      } else {
Unnecessary?

2023-01-15 08:11 UTC, zaynetro commented on packages/parchment/lib/src/heuristics/insert_rules.dart
> +      } else {
Indeed! Removed

2023-01-15 08:16 UTC, amantoux requested changes
Many thanks for this PR
On small change request

2023-01-15 08:19 UTC, amantoux approved these changes
LGTM
Many thanks!

2023-01-15 08:19 UTC, merged